-- AlterTable
ALTER TABLE "Bill" ALTER COLUMN "committee" DROP NOT NULL,
ALTER COLUMN "bill_kind" DROP NOT NULL,
ALTER COLUMN "who" DROP NOT NULL,
ALTER COLUMN "bill_class" DROP NOT NULL,
ALTER COLUMN "bill_date" DROP NOT NULL,
ALTER COLUMN "comm_seq" DROP NOT NULL,
ALTER COLUMN "bill_result" DROP NOT NULL,
ALTER COLUMN "match_url" DROP NOT NULL;
